# Generated by Django 2.0.1 on 2018-01-08 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('parent', models.CharField(max_length=50, verbose_name='Parent')),
                ('checkfield1', models.BooleanField(default=False)),
                ('checkfield2', models.BooleanField(default=False)),
                ('checkfield3', models.BooleanField(default=False)),
                ('checkfield4', models.BooleanField(default=False)),
            ],
        ),
    ]
